name: 'redshift'
version: '0.5.0'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets: ["target", dbt_packages] 

profile: 'lacolombe-data_town'

models:
  redshift:
    base:
      +materialized: ephemeral
    introspection:
      +materialized: ephemeral
    views:
      +materialized: view
